### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by DuilioAquino10** [SistemasTecTlaxiaco/infografia-de-las-librerias-DuilioAquino10#2]

**Comment by DuilioAquino10** [comment]
[Infografias-Librerias-Aquino Lopez Duilio Ruben.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-DuilioAquino10/files/6292373/Infografias-Librerias-Aquino.Lopez.Duilio.Ruben.pdf)

**Comment by Band-hi** [comment]
Calificación 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
